### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by brunoborges** [oracle/NoSQL-drivers#1]
Is it possible to rename this repository to `oracle-nosql-drivers`? Most GitHub repositories use the lower-case-dash-separator standard. Plus, adding "oracle-" prefix gives a clear indication this repository is related to Oracle NoSQL product.

**Comment by jinzha** [comment]
Hi Brunoborges,

I have renamed the repository to oracle-nosql-drivers, thanks!

Regards,
Jin
